### PR TITLE
Check if browser language is supported

### LINKED ISSUE #168: Web browsers in other languages - no data for test results
When using web browsers set with other languages than the one supported by Zonemaster, the results are not displayed.
The following error message is displayed : `No data for this test` but the data does exist.

The query sent to the api is wrong as it embarks the browser language which may be unknown to the backend.

If the browser is using an unsupported language, the results should be displayed in English. In this situation the query should set the `language` parameter to `en`.

See https://github.com/zonemaster/zonemaster/issues/918

### PR DESCRIPTION
**Pull request by pnax**
Do not blindly use the browser language. Verify that the GUI supports it, or force English.

Addresses https://github.com/zonemaster/zonemaster/issues/918
Closes #168

### CODE REVIEW

File: src/app/components/navigation/navigation.component.ts [hunk 1]
```diff
@@ -45,4 +50,9 @@ export class NavigationComponent implements OnInit {
   public setLanguage(lang: string) {
     this.translateService.use(lang);
   }
+
+  private isValidLanguage(lang: string) {
+    const validLanguages = [ 'en', 'fr', 'sv', 'da' ];
```
Comment (matsduf) [inline src/app/components/navigation/navigation.component.ts:55]: In PR #165 (not yet merged) I update all places where the language tags are mentioned to be in alphabetical order to have it consistent. I suggest that they are listed as
```
    const validLanguages = [ 'da', 'en', 'fr', 'sv' ];
```

**Review by matsduf — COMMENTED** [review]
For me this looks correct. I let @pamasse comment before I approve formally.

When this is merged I must remember to update #165.

File: src/app/components/navigation/navigation.component.ts (hunk 1 above)
Comment (pnax) [reply src/app/components/navigation/navigation.component.ts]: Fixed

**Comment by pnax** [comment]
> When this is merged I must remember to update #165.

Depending on which one is merged first, this can also be done here.

And this also adds a default variable, which might need a change in the documentation in the [Change default language section](https://github.com/zonemaster/zonemaster-gui/blob/ac535b101bca0324e42b6af399ea18594545c116/docs/TranslationGuide.md#change-default-language)

**Review by matsduf — APPROVED** [review]

**Comment by matsduf** [comment]
@pamasse, can you review this?

File: src/app/components/navigation/navigation.component.ts [hunk 2]
```diff
@@ -13,11 +13,16 @@ export class NavigationComponent implements OnInit {
   public isShrunk = false;
   public activeBackToTop = false;
   public lang = 'en';
+  private lang_default = 'en';
```
Comment (matsduf) [inline src/app/components/navigation/navigation.component.ts:16]: @pnax, if `private lang_default` should always be equal to `public lang` can't you just make them equal in the code? Or is there some use case for them being different?

Comment (pnax) [reply src/app/components/navigation/navigation.component.ts:16]: Well, the current code logic need 2 distinct variables because `this.lang` will be overwritten by the current browser language at [line 20 (b35695e)](https://github.com/zonemaster/zonemaster-gui/blob/b35695e3d5c688052f3154ee953d7a3622765a57/src/app/components/navigation/navigation.component.ts#L20) and I needed to keep track of the default language somewhere to set it as a fallback [line 24 (b35695e)](https://github.com/zonemaster/zonemaster-gui/blob/b35695e3d5c688052f3154ee953d7a3622765a57/src/app/components/navigation/navigation.component.ts#L24).

Looking at [line 19 (b35695e)](https://github.com/zonemaster/zonemaster-gui/blob/b35695e3d5c688052f3154ee953d7a3622765a57/src/app/components/navigation/navigation.component.ts#L19) and the call to [`setDefaultLang`](https://github.com/ngx-translate/core#methods), we can think that all this logic is not needed. But somehow the default language is not used as a fallback if the browser language does not match any supported languages. This is incidentally the issue that was raised. To be honest I don't know much of Angular nor NGX-translate, so I coded the logic and kept the current code in case. Maybe the `setDefaultLang` call can be removed.
