### PR TITLE
Fix the warning message during FAQ generation. fix #56

### LINKED ISSUE #56: Warnings when creating zip file
The zip file is created on the develop branch on the following commit:
```
commit fc3be71d73cb8e0c56633ae88684bbe2e34a7184
Merge: 8717a69 9dec49a
Author: pamasse <pa.masse@outlook.fr>
Date:   Fri May 17 16:02:01 2019 +0200

    Merge pull request #47 from pamasse/fix-empty-ns-default-test
    
    Fix sending empty ns when the advanced options are not open
```

Running `npm install` creates warnings. Can they be ignored? Can warnings always be ignored?
```
$ npm install
npm WARN @angular/compiler-cli@5.2.5 requires a peer of typescript@>=2.4.2 <2.7 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0 requires a peer of popper.js@^1.12.9 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.26.0 requires a peer of typescript@>=2.4.2 <2.7 but none is installed. You must install peer dependencies yourself.
npm WARN zonemaster-gui@3.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

updated 1 package and audited 10861 packages in 18.887s
found 293 vulnerabilities (29 low, 178 moderate, 84 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```
Running `npm run release` also creates some warnings. Can they be ignored?
```
$ npm run release

> zonemaster-gui@3.0.1 release /home/matsd/git/zonemaster-gui
> npm run build && node scripts/create_release.js

npm WARN invalid config loglevel="notice"

> zonemaster-gui@3.0.1 build /home/matsd/git/zonemaster-gui
> node scripts/faq.js && ng build -prod

{ [Error: ENOENT: no such file or directory, open './docs/FAQ/gui-faq-ru.md']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './docs/FAQ/gui-faq-ru.md' }

@angular/compiler-cli@5.2.5 requires typescript@'>=2.4.2 <2.7.0' but 2.7.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.7.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".

(...)
```
After running `npm install typescript@'>=2.4.2 <2.7.0'` and then re-running `npm run release` the typescript warning disappeared.

### PR DESCRIPTION
**Pull request by pamasse**
Fix the warning message during FAQ generation. fix #56

### CODE REVIEW

**Comment by mattias-p** [comment]
@pamasse Please update this PR according to your comments in #56.

File: scripts/faq.js [hunk 1]
```diff
@@ -33,7 +33,9 @@ const getFaq = (lang) => {
 
 fs.readdir('./src/assets/i18n', (err, files) => {
   files.forEach(filename => {
-    getFaq(filename.split('.')[0]);
+    if(filename !== 'ru.json') {
+      getFaq(filename.split('.')[0]);
```
Comment (matsduf) [inline scripts/faq.js]: I see no reason for this "fix". Remove [ru.json] instead. If we get a Russian translation of Zonemaster this file could be recreated.

[ru.json]: https://github.com/zonemaster/zonemaster-gui/blob/master/src/assets/i18n/ru.json
